// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Hand-authored OpenAPI 3.0 contract for Oracle Fusion Cloud's generic Enterprise Scheduler (ESS) REST API (introduced in release 23B), used to submit and monitor scheduled process/job requests.
# Oracle does not publish a machine-readable spec for this API - this document was reconstructed from Oracle's public REST API reference documentation (docs.oracle.com .../farca/api-scheduler.html and .../farca/op-ess-rest-scheduler-v1-requests-get.html /-post.html). Verify field names/enums against the target instance's actual release before use.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://your-fusion-instance.fa.us2.oraclecloud.com/ess/rest/scheduler/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, timeout: config.timeout, forwarded: config.forwarded, poolConfig: config.poolConfig, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, validation: config.validation};
        do {
            if config.http1Settings is ClientHttp1Settings {
                ClientHttp1Settings settings = check config.http1Settings.ensureType(ClientHttp1Settings);
                httpClientConfig.http1Settings = {...settings};
            }
            if config.http2Settings is http:ClientHttp2Settings {
                httpClientConfig.http2Settings = check config.http2Settings.ensureType(http:ClientHttp2Settings);
            }
            if config.cache is http:CacheConfig {
                httpClientConfig.cache = check config.cache.ensureType(http:CacheConfig);
            }
            if config.responseLimits is http:ResponseLimitConfigs {
                httpClientConfig.responseLimits = check config.responseLimits.ensureType(http:ResponseLimitConfigs);
            }
            if config.secureSocket is http:ClientSecureSocket {
                httpClientConfig.secureSocket = check config.secureSocket.ensureType(http:ClientSecureSocket);
            }
            if config.proxy is http:ProxyConfig {
                httpClientConfig.proxy = check config.proxy.ensureType(http:ProxyConfig);
            }
        }
        http:Client httpEp = check new (serviceUrl, httpClientConfig);
        self.clientEp = httpEp;
        return;
    }

    # Query scheduled process (ESS) job requests
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Matching job requests 
    resource isolated function get requests(map<string|string[]> headers = {}, *QueryJobRequestsQueries queries) returns RequestQueryResponse|error {
        string resourcePath = string `/requests`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get a specific job request by ID
    #
    # + headers - Headers to be sent with the request 
    # + return - Job request detail 
    resource isolated function get requests/[int requestId](map<string|string[]> headers = {}) returns RequestDetails|error {
        string resourcePath = string `/requests/${getEncodedUri(requestId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Submit a new scheduled process (ESS) job request
    #
    # + headers - Headers to be sent with the request 
    # + return - Job request created 
    resource isolated function post requests(SubmitRequestBody payload, map<string|string[]> headers = {}) returns SubmitRequestResponse|error {
        string resourcePath = string `/requests`;
        http:Request request = new;
        json jsonBody = payload.toJson();
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }
}
