// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# An inline schedule for a job request, defining when and how often it recurs. Supply this instead of `scheduleId` to define the schedule with the request rather than referencing one that already exists on the instance.
public type ScheduleBase record {
    # Recurrence patterns that generate the schedule's occurrences. Multiple patterns combine, so one schedule can mix, for example, a weekday rule with a month-end rule.
    Recurrence[] recurrences?;
    # Olson database format, e.g. Asia/Colombo.
    string timezone?;
    # Date-times to skip, removing occurrences the recurrence patterns would otherwise generate.
    string[] exclusions?;
    # Additional date-times to run at, over and above the occurrences the recurrence patterns generate.
    string[] inclusions?;
};

# A subscription that has the scheduler call an external endpoint as the job request changes state, as an alternative to polling `getJobRequest`.
public type CallbackSubscriptionRequest record {
    # Scheme, host and port of the callback endpoint, e.g. `https://callbacks.example.com`.
    string callbackUrlPrefix;
    # OAuth2 client identifier. Applies when `securityScheme` is `DIRECT_OAUTH`.
    string clientId?;
    # Path of the callback endpoint, appended to `callbackUrlPrefix` to form the URL the scheduler invokes.
    string callbackResourcePath;
    # How the scheduler authenticates when invoking the callback. `OWSM_GPA` and `OWSM_LPA` use Oracle Web Services Manager global and local policy attachments respectively; `DIRECT_OAUTH` uses the OAuth2 client credentials supplied in the fields below.
    "OWSM_GPA"|"OWSM_LPA"|"DIRECT_OAUTH" securityScheme = "OWSM_GPA";
    # OAuth2 token endpoint the scheduler obtains a token from. Applies when `securityScheme` is `DIRECT_OAUTH`.
    string accessTokenUri?;
    # OAuth2 client secret. Applies when `securityScheme` is `DIRECT_OAUTH`.
    string clientSecret?;
    # Credential Store Framework (CSF) key holding the OAuth2 client credentials, as an alternative to passing `clientId` and `clientSecret` directly. The misspelling of "oauth2" is Oracle's and is kept so the payload matches the API.
    string ouath2ClientCsfKey?;
};

# One recurrence pattern within a schedule, expressed as an iCalendar recurrence rule with an optional active window.
public type Recurrence record {
    # RFC 5545 RRULE recurrence pattern.
    string icalString;
    # Date-time after which this pattern stops producing occurrences.
    string endDate?;
    # Earliest date-time at which this pattern starts producing occurrences.
    string startDate?;
};

# Represents the Queries record for the operation: getJobRequest
public type GetJobRequestQueries record {
    # Comma-separated list of link relations to return, e.g. "links=cancel". Filters the `links` collection in the response.
    string links?;
    # Comma-separated list of fields to return, e.g. "fields=requestId".
    string fields?;
    # Comma-separated list of fields to exclude from the information returned, e.g. "excludeFields=jobDefinitionId".
    string excludeFields?;
};

# A single job-specific parameter carried with a job request. The scheduler passes these through to the job definition being run.
public type RequestParameter record {
    # Data type of `value`, so the scheduler can interpret it as the type the job definition expects.
    "BOOLEAN"|"LONG"|"INTEGER"|"DATETIME"|"STRING" paramType;
    # Scope the parameter applies to. Relevant for job sets, where a parameter can target an individual step rather than the set as a whole.
    string scope?;
    # Name of the parameter, as declared by the job definition.
    string name;
    # Value of the parameter. Always carried as a string and interpreted according to `paramType`.
    string value?;
};

# A page of job requests matching a `queryJobRequests` call.
public type RequestQueryResponse record {
    # Zero-based index of the page these results come from.
    int pageIndex?;
    # Number of requests returned in `items`.
    int count?;
    # Hypermedia links for the collection, such as paging links.
    RequestLink[] links?;
    # The job requests on this page.
    RequestDetails[] items?;
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

# A job request to submit to the Enterprise Scheduler.
public type SubmitRequestBody record {
    # Product the job definition belongs to. Used together with `application` to narrow where the scheduler looks the definition up.
    string product?;
    # Metadata object ID for the job definition or job set being submitted.
    string jobDefinitionId;
    # Job-specific parameters passed through to the job definition.
    RequestParameter[] requestParameters?;
    # Human-readable description of the request, echoed back by `getJobRequest` and `queryJobRequests`.
    string description?;
    # Verbosity the scheduler logs the request's execution at.
    string requestLogLevel?;
    # Request priority, 0-9. Oracle applies its own default (documented as 4) when omitted.
    @constraint:Int {minValue: 0, maxValue: 9}
    int priority?;
    # Number of automatic retries on failure. Oracle applies its own default (documented as 0) when omitted.
    int retries?;
    # Inline schedule that makes the request recur. Mutually exclusive with `scheduleId`.
    ScheduleBase schedule?;
    # The request execution context of the current job request. Only used when creating sub-requests - it identifies the running request that is creating them.
    RequestExecutionContextIn requestExecutionContext?;
    # Application the job definition is deployed in. Used together with `product` to narrow where the scheduler looks the definition up.
    string application?;
    # Caller-assigned category for the request, available afterwards as a `q` filter on `queryJobRequests`.
    string requestCategory?;
    # When the request becomes eligible to run. Omit to have the scheduler run it as soon as it can.
    string startTime?;
    # Whether schedule occurrences whose time has already passed are still executed. Oracle applies its own default (documented as true) when omitted.
    boolean executePast?;
    # Point after which the request, or the remaining occurrences of its schedule, are no longer run.
    string endTime?;
    # Callback subscription notified as the request changes state, as an alternative to polling `getJobRequest`.
    CallbackSubscriptionRequest callbackSubscription?;
    # Maximum time the request is allowed to run before the scheduler times it out. A request stopped this way reports an `errorType` of `TIMEOUT`.
    int requestTimeout?;
    # Identifier of a schedule that already exists on the instance, used instead of defining one inline. Mutually exclusive with `schedule`.
    string scheduleId?;
};

# Represents the Queries record for the operation: queryJobRequests
public type QueryJobRequestsQueries record {
    # SCIM-style filter, e.g. state eq "RUNNING". Queryable fields include requestId, absParentRequestId, description, application, product, requestCategory, runAsUser, executionType, jobDefinitionId, state, priority, processStartTime, processEndTime, requestedStartTime, requestedEndTime, submissionTime, parentRequestId, elapsedTime, submitter, requestType, errorType, completedTime, and more.
    string q?;
    # fieldName[:asc|desc], e.g. name:asc
    string orderBy?;
    # Comma-separated list of request IDs to return.
    string id?;
    # Comma-separated list of fields to include in the response.
    string fields?;
    # Comma-separated list of fields to exclude from the response.
    string excludeFields?;
};

# Full detail of a single Enterprise Scheduler job request, covering how it was submitted, where it has reached in its lifecycle, and which actions are currently available on it.
public type RequestDetails record {
    # User who submitted the request.
    string submitter?;
    # Metadata object ID of the job definition or job set the request runs.
    string jobDefinitionId?;
    # Where the request sits in the scheduler's request hierarchy - a one-off (`SINGLETON`), a recurring parent or one of the children it generates (`RECUR_PARENT`, `RECUR_CHILD`), the `JOBSET_` prefixed equivalents for job sets and their steps, or a sub-request created by another running request (`SUB_REQUEST`).
    "SINGLETON"|"RECUR_PARENT"|"RECUR_CHILD"|"JOBSET_SINGLETON"|"JOBSET_STEP"|"JOBSET_RECUR_PARENT"|"JOBSET_RECUR_CHILD"|"SUB_REQUEST"|"UNKNOWN" requestType?;
    # Class of failure when the request did not succeed. `SYSTEM` for scheduler or infrastructure faults, `BUSINESS` for faults raised by the job itself, `TIMEOUT` when the request exceeded its `requestTimeout`, and the two `MIXED_` prefixed values for job sets whose steps failed in more than one of those ways.
    "SYSTEM"|"BUSINESS"|"TIMEOUT"|"MIXED_NON_BUSINESS"|"MIXED_BUSINESS" errorType?;
    # Time the request reached a terminal state and the scheduler finished with it.
    string completedTime?;
    # Job-specific parameters the request was submitted with.
    RequestParameter[] requestParameters?;
    # Description supplied when the request was submitted.
    string description?;
    # Priority the request was submitted with, 0-9.
    int priority?;
    # Time the request was submitted to the scheduler.
    string submissionTime?;
    # Schedule driving the request. Present on recurring requests.
    ScheduleBase schedule?;
    # Time the request was asked to start at, from either `startTime` on submission or the schedule occurrence it came from.
    string requestedStartTime?;
    # Application the job definition is deployed in.
    string application?;
    # Time the request actually began executing. Unset while it is still waiting to be picked up.
    string processStartTime?;
    # ID of the request.
    int requestId?;
    # Whether `cancel` is available on the request in its current state.
    boolean isCancellable?;
    # Time the request finished executing.
    string processEndTime?;
    # Hypermedia links for this request, covering related requests and the actions currently available on it. Narrow the set returned with the `links` query parameter.
    RequestLink[] links?;
    # Current lifecycle state of the request, e.g. WAIT, READY, RUNNING, SUCCEEDED, ERROR or CANCELLED. Not restricted to those values - the scheduler defines further states, so treat this as an open set rather than a fixed one.
    string state?;
    # Human-readable explanation of `state`, carrying the reason when the request did not succeed.
    string stateDescription?;
    # Whether `hold` is available on the request in its current state.
    boolean isHoldable?;
    # Whether `forceCancel` is available on the request in its current state, for when an ordinary `cancel` does not take effect.
    boolean isForceCancelAllowed?;
    # How long the request has been running, or ran for, in milliseconds.
    int elapsedTime?;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

# A hypermedia link on a job request, giving the URL of a related resource or of an action that can be performed on the request.
public type RequestLink record {
    # Relation identifying what the link points to. `self`, `parentRequest`, `absParentRequest` and `instanceParent` address requests; `cancel`, `forceCancel`, `hold`, `release` and `subscribe` address actions on this request; `permissions` and `executionStatus` address further detail about it.
    "self"|"parentRequest"|"cancel"|"forceCancel"|"hold"|"release"|"subscribe"|"permissions"|"executionStatus"|"absParentRequest"|"instanceParent" rel;
    # URL of the related resource or action.
    string href;
};

# The outcome of submitting a job request.
public type SubmitRequestResponse record {
    # Hypermedia links for the new request, typically including `self` and the actions currently available on it.
    RequestLink[] links?;
    # ID of the newly created job request. Pass this to `getJobRequest` to track it.
    int id?;
};

# Identifies the running job request that is submitting this one, so the scheduler records the new request as its sub-request.
public type RequestExecutionContextIn record {
    # Opaque handle of the running request. Available only from inside an executing ESS job, so it cannot be fabricated by an external caller.
    string requestHandle;
    # ID of the running request that is creating the sub-request.
    int requestId;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:OAuth2ClientCredentialsGrantConfig|http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
