// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

public type ScheduleBase record {
    Recurrence[] recurrences?;
    # Olson database format, e.g. Asia/Colombo.
    string timezone?;
    string[] exclusions?;
    string[] inclusions?;
};

public type CallbackSubscriptionRequest record {
    string callbackUrlPrefix;
    string clientId?;
    string callbackResourcePath;
    "OWSM_GPA"|"OWSM_LPA"|"DIRECT_OAUTH" securityScheme = "OWSM_GPA";
    string accessTokenUri?;
    string clientSecret?;
    string ouath2ClientCsfKey?;
};

public type Recurrence record {
    # RFC 5545 RRULE recurrence pattern.
    string icalString;
    string endDate?;
    string startDate?;
};

# Represents the Queries record for the operation: getJobRequest
public type GetJobRequestQueries record {
    # Comma-separated list of link relations to return, e.g. "links=cancel". Filters the `links` collection in the response.
    string links?;
    # Comma-separated list of fields to return, e.g. "fields=requestId".
    string fields?;
    # Comma-separated list of fields to exclude from the information returned, e.g. "excludeFields=jobDefinitionId".
    string excludeFields?;
};

public type RequestParameter record {
    "BOOLEAN"|"LONG"|"INTEGER"|"DATETIME"|"STRING" paramType;
    string scope?;
    string name;
    string value?;
};

public type RequestQueryResponse record {
    int pageIndex?;
    int count?;
    RequestLink[] links?;
    RequestDetails[] items?;
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

# Represents the Queries record for the operation: queryJobRequests
public type QueryJobRequestsQueries record {
    # SCIM-style filter, e.g. state eq "RUNNING". Queryable fields include requestId, absParentRequestId, description, application, product, requestCategory, runAsUser, executionType, jobDefinitionId, state, priority, processStartTime, processEndTime, requestedStartTime, requestedEndTime, submissionTime, parentRequestId, elapsedTime, submitter, requestType, errorType, completedTime, and more.
    string q?;
    # fieldName[:asc|desc], e.g. name:asc
    string orderBy?;
    # Comma-separated list of request IDs to return.
    string id?;
    # Comma-separated list of fields to include in the response.
    string fields?;
    # Comma-separated list of fields to exclude from the response.
    string excludeFields?;
};

public type SubmitRequestBody record {
    string product?;
    # Metadata object ID for the job definition or job set being submitted.
    string jobDefinitionId;
    RequestParameter[] requestParameters?;
    string description?;
    string requestLogLevel?;
    # Request priority, 0-9. Oracle applies its own default (documented as 4) when omitted.
    @constraint:Int {minValue: 0, maxValue: 9}
    int priority?;
    # Number of automatic retries on failure. Oracle applies its own default (documented as 0) when omitted.
    int retries?;
    ScheduleBase schedule?;
    # The request execution context of the current job request. Only used when creating sub-requests - it identifies the running request that is creating them.
    RequestExecutionContextIn requestExecutionContext?;
    string application?;
    string requestCategory?;
    string startTime?;
    # Whether schedule occurrences whose time has already passed are still executed. Oracle applies its own default (documented as true) when omitted.
    boolean executePast?;
    string endTime?;
    CallbackSubscriptionRequest callbackSubscription?;
    int requestTimeout?;
    # Mutually exclusive with `schedule`.
    string scheduleId?;
};

public type RequestDetails record {
    string submitter?;
    string jobDefinitionId?;
    "SINGLETON"|"RECUR_PARENT"|"RECUR_CHILD"|"JOBSET_SINGLETON"|"JOBSET_STEP"|"JOBSET_RECUR_PARENT"|"JOBSET_RECUR_CHILD"|"SUB_REQUEST"|"UNKNOWN" requestType?;
    "SYSTEM"|"BUSINESS"|"TIMEOUT"|"MIXED_NON_BUSINESS"|"MIXED_BUSINESS" errorType?;
    string completedTime?;
    RequestParameter[] requestParameters?;
    string description?;
    int priority?;
    string submissionTime?;
    ScheduleBase schedule?;
    string requestedStartTime?;
    string application?;
    string processStartTime?;
    int requestId?;
    boolean isCancellable?;
    string processEndTime?;
    RequestLink[] links?;
    string state?;
    string stateDescription?;
    boolean isHoldable?;
    boolean isForceCancelAllowed?;
    # Milliseconds.
    int elapsedTime?;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

public type RequestLink record {
    "self"|"parentRequest"|"cancel"|"forceCancel"|"hold"|"release"|"subscribe"|"permissions"|"executionStatus"|"absParentRequest"|"instanceParent" rel;
    string href;
};

public type SubmitRequestResponse record {
    RequestLink[] links?;
    int id?;
};

public type RequestExecutionContextIn record {
    string requestHandle;
    int requestId;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:OAuth2ClientCredentialsGrantConfig|http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
